### ISSUE TITLE
GUI_ProjectBackup – Backup a Project

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#29]
A project in TMG is a number of Firefox files.
A project in HRE is a single H2 database file.
This makes this much easier.
An unscientific test showed that zipped H2 databases shrunk to between two thirds and a few percent of the original files.
Just zipping and unzipping H2 files is the easiest solution.
Another way would be to export each table to cvs before zipping, which has the advantage of being readable outside of HRE and H2.

**Comment by HREferg** [comment]
This is an area we had not come to a conclusion as we weren’t sure we knew all the facts.

 

There are 2 issues (1) what are we backing up/restoring? and (2) what are the available & best tools?

 

1.	The backup set is not just the H2 database. An HRE ‘fileset’ will consist of the H2 database, the ‘ancillary data’ that resides outside of H2 (in XML or JSON or whatever) and, optionally folder(s) of external data (such as image files) that the user may wish to include in the backup.
2.	I understand that the possible backup methods are (a) to use the H2 Backup command (which creates a zip file); (b) to use a native Java command (ZipOutputStream?), (c) to create a csv file, (d) others?

 

Personally I’d favour the zip method, as zip files are well understood, but we then also need to be able to add the other 2 parts to the zip package.

I understand the csv file means it’s readable by external methods, but suspect, since we’re using a well-populated DB, that the space savings will be much lower than using zip.  Of course, one could create a csv file and then zip it, but this is a 2-stage process. 

 

Your input would be appreciated (I note you seem to be having issues creating a csv file!

 

Don

**Comment by MichaelErichsen** [comment]
It is not much extra work to do both zipped H2 plus the rest and zipped csv plus the rest, so I suggest we do both now.
When we start testing with large databases we then might choose to eliminate one of them.

**Comment by ricko2001** [comment]
I just wanted to remind folks about zip file issues:
File and archive max size
File path Unicode chars

No need for a reply....

**Comment by HREferg** [comment]
Closed - current Build of HRE performs zip of project H2 database
