### ISSUE TITLE
Deployment: Add HRE.bat and HRE.sh

### ISSUE THREAD

**Issue by MichaelErichsen** [History-Research-Environment/HRE--History-Research-Environment#62]
Write scripts and add them to rootfiles.
Add documentation to Cookbook and website.

**Comment by MichaelErichsen** [comment]
Examples rom h2 to copy from:

@echo off
if "%JAVA_HOME%"=="" echo Error: JAVA_HOME is not defined.
if "%1"=="clean" rmdir /s /q temp bin 2>nul
if not exist temp mkdir temp
if not exist bin mkdir bin
"%JAVA_HOME%/bin/javac" -sourcepath src/tools -d bin src/tools/org/h2/build/*.java
"%JAVA_HOME%/bin/java" -Xmx256m -cp "bin;%JAVA_HOME%/lib/tools.jar;temp" org.h2.build.Build %*

And:

#!/bin/sh
if [ -z "$JAVA_HOME" ] ; then
  if [ -d "/System/Library/Frameworks/JavaVM.framework/Home" ] ; then
    export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home
  else
    echo "Error: JAVA_HOME is not defined."
  fi
fi
if [ "$1" = "clean" ] ; then rm -rf temp bin ; fi
if [ ! -d "temp" ] ; then mkdir temp ; fi
if [ ! -d "bin" ] ; then mkdir bin ; fi
"$JAVA_HOME/bin/javac" -sourcepath src/tools -d bin src/tools/org/h2/build/*.java
"$JAVA_HOME/bin/java" -Xmx256m -cp "bin:$JAVA_HOME/lib/tools.jar:temp" org.h2.build.Build $@

**Comment by HREferg** [comment]
Michael – I don’t think this JAVA_HOME stuff is needed – because you’ve built HRE code with a basic Eclipse body, that seems to have been covered already. Certainly I can download and run one of your builds without having JAVA_HOME set (it was only needed for the mockup).

Am building the execution of the HRE.bat (or sh) into the cookbook next version, on the assumption this has been done.

Don

**Comment by MichaelErichsen** [comment]
Has been added and will be deployed with the next build.
